calendars:
  dayspring:
    url:
      https://dayspringchristianchurch.ccbchurch.com/churchwide_calendar.ics?campus_id=1
    jexl:
      (summary != "Sunday School") && (summary != "Elders Meeting") && (summary !="Private Event") && !("HOA" in summary)
